/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    Cart: typeof import('./components/Cart.vue')['default']
    CategoriesTable: typeof import('./components/categories/CategoriesTable.vue')['default']
    CategoryForm: typeof import('./components/category/CategoryForm.vue')['default']
    CategoryTable: typeof import('./components/category/CategoryTable.vue')['default']
    FieldImage: typeof import('./components/FieldImage.vue')['default']
    FieldInput: typeof import('./components/FieldInput.vue')['default']
    FieldSelect: typeof import('./components/FieldSelect.vue')['default']
    Inventory: typeof import('./components/inventory/Inventory.vue')['default']
    InventoryForm: typeof import('./components/inventory/InventoryForm.vue')['default']
    InventoryTable: typeof import('./components/inventory/InventoryTable.vue')['default']
    LocationForm: typeof import('./components/location/LocationForm.vue')['default']
    LocationTable: typeof import('./components/location/LocationTable.vue')['default']
    ProductDeleteDialog: typeof import('./components/products/ProductDeleteDialog.vue')['default']
    ProductDetail: typeof import('./components/products/ProductDetail.vue')['default']
    ProductForm: typeof import('./components/products/ProductForm.vue')['default']
    ProductTable: typeof import('./components/products/ProductTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    ToggleSwitch: typeof import('./components/ToggleSwitch.vue')['default']
  }
}
